### ISSUE TITLE
Profile does not exist for this device

### ISSUE THREAD

**Issue by smathieson** [udifuchs/icc-brightness#1]
For some reason seems to have stopped working in debian SID.

The command:
"colormgr find-profile-by-filename brightness_583_1060.icc"
Finds the following object path:
"/org/freedesktop/ColorManager/profiles/icc_f1331094da4d3aae46271d681fc04c49_samuel_1000"

Then the command:
"colormgr device-make-profile-default 'xrandr-Lenovo Group Limited' /org/freedesktop/ColorManager/profiles/icc_f1331094da4d3aae46271d681fc04c49_samuel_1000"
Errors out the following: 
"profile object path '/org/freedesktop/ColorManager/profiles/icc_f1331094da4d3aae46271d681fc04c49_samuel_1000' does not exist for this device"

This is not related to the python script, seems the error is in colormgr. Any idea what might be wrong?

Thanks,
Sam.

**Comment by smathieson** [comment]
Here is your python script modified to "fix" this issue.
Changes:
colormgr device-add-profile will run every time in a try pass block (seems to fail sometimes otherwise???)
DEVICE_ID replaced by a function that uses colormgr get-devices-by-kind display

Seems to work like this. Would be interested in knowing if your original script still runs in your laptop. I don't know why it just stopped working.

[icc-brightness.zip](https://github.com/udifuchs/icc-brightness/files/1773786/icc-brightness.zip)

**Comment by udifuchs** [comment]
I applied your patch with a few changes. I'm not sure why colormgr is behaving this way. I sometimes get the error 'The profile was not added in time' during import-profile, but I haven't seen your error.
