### ISSUE TITLE
Dell xps 7590 OLED

### ISSUE THREAD

**Issue by MuDiAhmed** [udifuchs/icc-brightness#17]
I followed the read me file instructions, but I was able only to dim the screen one time(don't know how) and that's it.
I tried `./icc-brightness watch` nothing happens.
I run `sudo make install` after restart the screen was at the same brightness level, but that's it.
tried changing the brightness from the system settings and keyboard shortcut, but no luck.

any idea what I should be looking for to debug or make it work?

additional info:
OS: Ubuntu 18.04
kernel release: 5.0.0-32-generic

**Comment by DPons97** [comment]
Hi, I had your same problem and I just managed to solve it. I was able to dim the screen brightness only few times before it suddenly stopped working.
(I'm using Ubuntu 19.10 on the same 7590 Dell laptop, but I'm pretty sure this fix is valid for every os version). 
The 'icc-brightness' python script gets os birghtness values from folder `/sys/class/backlight/intel-backlight.` 
However I noticed that my laptop had its own "brightness folder", different from the intel one:
`/sys/class/backlight/dell-backlight`.
Looking at the 'birghtness' and 'max_brightness' files inside the two folders I noticed that only the dell one was reacting to the change in screen brightness through system settings.

So, to solve the issue, just edit the line (inside "icc-birghtness" script) 
`BACKLIGHT_PATH = '/sys/class/backlight/intel_backlight'` 
to 
`BACKLIGHT_PATH = '/sys/class/backlight/dell_backlight'`

My guess is that when I installed the script for the first time I was still using Intel drivers, and a later dell update must have forced its color management to override the previous one. 
I hope this solves your issue too, maybe this can be also useful for other manufacturer laptops other than Dell. Just check your backlight directory and see if there's some other folder other than Intel's.

**Comment by MuDiAhmed** [comment]
Thanks for your help. 
Yeah I noticed this directory when I was working on a different script that uses `Xrendr` instead of `ICC`, will give it a try.

can I ask you 1 more questions, not related to the brightness isssue.
1. when your laptop on suspend, do you notice any screen flickering, mine have a white line that appear on the top part of the screen every like 8 seconds?
Thanks

**Comment by DPons97** [comment]
Well maybe this Issue will help someone else having the same problem.
About your second question: actually no, I didn't notice any kind of flickering. 
As for now, the oled panel with the icc script is working fine.

**Comment by MuDiAhmed** [comment]
I will try to make a fresh install for Ubuntu 19.04 and check the flickering issue.
Again many thanks for your help and quick reply
