### ISSUE TITLE
Brightness suddenly drops

### ISSUE THREAD

**Issue by balazsorban44** [udifuchs/icc-brightness#20]
I am using a Lenovo ThinkPad X1 Yoga OLED, and sometimes, the brightness suddenly drops, and the screen becomes very dark. Using the keys (`Fn` + `F6`) it gets brighter again, but not every keypress is registered. That results in that when the brightness indicator is full, the brightness of the screen is still not at the max brightness. I then have to reduce the brightness again and try several times to increase the brightness to max.

**Comment by brainygamer** [comment]
I'm experiencing the same, just as you describe.

**Comment by vitusya** [comment]
same with me

**Comment by vitusya** [comment]
Using ubuntu 19.10 with "night light on" feature, touring off night light solves issue for me.

**Comment by uipoet** [comment]
Until the actual bug is fixed, I've been able to resolve this with `icc-brightness clear` and `icc-brightness apply` on my Thinkpad Extreme (gen 2) in Arch Linux.

**Comment by balazsorban44** [comment]
Looks like disabling Auto Brightness in the settings solved the issue for me 🤦.
