### ISSUE TITLE
How does it compare with setting brightness via xrandr?

### ISSUE THREAD

**Issue by alesguzik** [udifuchs/icc-brightness#3]
How does it compare to things like `xrandr --output eDP-1 --brightness 0.7`? That's what I use, and it applies to the whole display on my OLED X1 Yoga Gen2. Is this more color-accurate? Does it make sense to use compared to xrandr brightness?

**Comment by udifuchs** [comment]
It should be exactly the same. The difference is that xrandr does not work
with Wayland.
