### ISSUE TITLE
max-brightness not working

### ISSUE THREAD

**Issue by PixsaOJ** [udifuchs/icc-brightness#40]
Hi, I am on Manjaro, Nvidia 1050 Ti, HP Pavilion 15 Gaming + Philips 223V monitor.
Used "icc-brightness-gnome-git" package to install from AUR.

When I try this command : `brightness max-brightness` I get errors.

```bash
➜  ~ icc-brightness brightness max-brightness
Traceback (most recent call last):
  File "/usr/bin/icc-brightness", line 157, in <module>
    main()
  File "/usr/bin/icc-brightness", line 148, in main
    brightness = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: 'brightness'
```

icc-brightness watch command is working. It's little jumpy, but it's fine. Could be smoother.

**Comment by gitpushoriginmaster** [comment]
As the last line of the error message says - please consider using int values.
Example: `icc-brightness 80 100` will set the brightness to 80%
